name: higherANML
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - torchvision
  - pytorch
  - tqdm
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - pip:
    - higher
    - gdown
