#
# Config for continual meta-test of Classifier-Basline models on Omniglot. Fine-tunes just the classifier.
#

# Dataset
dataset: omni
train_examples: 15
test_examples: 5

# Test Method
eval_method: zero_shot
reinit_method: lstsq
reinit_params: classifier.linear
init_size: 3295
batch_size: 512
classes: 600
