#
# Config for reproducing OML results on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 200
remember_size: 100
remember_only: false
inner_lr: 0.001
outer_lr: 0.001

epochs: 25000
seed: 1

# Model Architecture
model: oml

# Optimization Configuration
inner_params: pn
outer_params: all
output_layer: pn.2

eval_steps: [10000, 25000]
eval: !include eval-sweep-inet-oml.yml
