#
# Current best known config for training an ANML-like model on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
method: iid
batch_size: 256
epochs: 90
seed: 1

# Model Architecture
model: classifier
model_args:
  encoder: resnet18
  classifier: linear-classifier
  classifier_args: {num_classes: 64}

# Optimization
optimizer: SGD
optimizer_args:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
lr_scheduler: StepLR
lr_scheduler_args:
  step_size: 30
  gamma: 0.1

# Evaluation
save_freq: 125
eval_steps: [7500, 25000]
eval:
  - olft: !include eval-sweep-inet-1FC.yml
  - unfrozen: !include eval-sweep-inet-unfrozen.yml
  - olft-oracle: !include eval-sweep-inet-iid-1FC.yml
  - unfrozen-oracle: !include eval-sweep-inet-iid-unfrozen.yml

