#
# Current best known config for training an ANML-like model on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 200
remember_size: 100
remember_only: false
inner_lr: 0.001
outer_lr: 0.001

epochs: 200000
seed: 1

# Model Architecture
model: sanml
model_args:
    rln_chs: 256

# Optimization Configuration
inner_params: [rln, fc]
outer_params: all  # special keyword for "all parameters"
output_layer: fc
