#
# Config for training SANML in standard, non-meta-learned fashion on Omniglot data.
#

# Dataset
dataset: omni
train_size: 15

# Training Configuration
train_method: iid
batch_size: 256
epochs: 10
seed: 12345

# Model Architecture
model: classifier
model_args:
  encoder: convnet
  encoder_args:
    num_blocks: 3
    num_filters: 256
    padding: 0
    pool_size: [2, 2, 0]
  classifier: linear-classifier
  classifier_args: {num_classes: 1000}

# Optimization
lr: 0.001

# Evaluation
save_freq: 57
eval_steps: [300, 10000]
eval:
  - olft: !include eval-sweep-omni-1FC.yml
  - unfrozen: !include eval-sweep-omni-unfrozen.yml
  - olft-oracle: !include eval-sweep-omni-iid-1FC.yml
  - unfrozen-oracle: !include eval-sweep-omni-iid-unfrozen.yml
