#
# Current best known config for training an ANML-like model on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 200
remember_size: 100
remember_only: false
inner_lr: 0.001
outer_lr: 0.001

epochs: 25000
seed: 1

# Model Architecture
model: classifier
model_args:
  encoder: resnet18
  encoder_args: {}
  classifier: linear-classifier
  classifier_args: {num_classes: 64}

# Optimization Configuration
inner_params: classifier
outer_params: all
output_layer: classifier.linear

eval_steps: [10000, 25000]
eval:
  - olft: !include eval-sweep-inet-1FC.yml
  - unfrozen: !include eval-sweep-inet-unfrozen.yml
  - olft-oracle: !include eval-sweep-inet-iid-1FC.yml
  - unfrozen-oracle: !include eval-sweep-inet-iid-unfrozen.yml
