#
# Config for standard training of ANML for continuous learning on Omniglot.
#

# Dataset
dataset: omni
train_size: 20

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 0
remember_size: 64
remember_only: false
inner_lr: 0.1
outer_lr: 0.001

epochs: 25000
seed: 1

# Model Architecture
model: sanml
model_args:
    rln_chs: 256
    pool_rln_output: false

# Optimization Configuration
inner_params: [rln, fc]
outer_params: all  # special keyword for "all parameters"
output_layer: fc

eval_steps: [10000, 25000]
eval: !include eval-sweep-omni-anml.yml
