#
# Config for reproducing OML results on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 200
remember_size: 64
remember_only: false
inner_lr: 0.01
outer_lr: 0.0001

epochs: 200000
seed: 1

# Model Architecture
model: oml

# Optimization Configuration
inner_params: [pn]
outer_params: all  # special keyword for "all parameters"
output_layer: output_layer
